// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/core/pb/block.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blocks struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_ad6040316522730e, []int{0}
}
func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (dst *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(dst, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	Height               uint64         `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	ParentHash           []byte         `protobuf:"bytes,4,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_ad6040316522730e, []int{1}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Prevhash             []byte   `protobuf:"bytes,2,opt,name=Prevhash,proto3" json:"Prevhash,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_ad6040316522730e, []int{2}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *BlockHeader) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Blocks)(nil), "corepb.Blocks")
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/core/pb/block.proto", fileDescriptor_block_ad6040316522730e)
}

var fileDescriptor_block_ad6040316522730e = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x26, 0x0d, 0x3a, 0xa9, 0x97, 0x51, 0x24, 0x14, 0x91, 0x10, 0x10, 0x02, 0x62,
	0x82, 0xf5, 0xd0, 0xbb, 0xa7, 0x9e, 0x44, 0x96, 0xfe, 0x81, 0x4d, 0xba, 0x24, 0xc1, 0x26, 0xbb,
	0xee, 0xae, 0x82, 0x3f, 0xc8, 0xff, 0x29, 0x99, 0xa4, 0x6d, 0x7a, 0xf3, 0xf6, 0xe6, 0x9b, 0x37,
	0xef, 0x2d, 0x0b, 0xcf, 0x55, 0xe3, 0xea, 0xaf, 0x22, 0x2b, 0x55, 0x9b, 0xef, 0x84, 0xd6, 0x7b,
	0xf9, 0x93, 0x57, 0xea, 0xe9, 0x20, 0x4b, 0x65, 0x64, 0xae, 0x8b, 0xbc, 0xd8, 0xab, 0xf2, 0x23,
	0xd3, 0x46, 0x39, 0x85, 0x41, 0x0f, 0x75, 0xb1, 0x5c, 0xff, 0xef, 0xd4, 0x19, 0xd1, 0x59, 0x51,
	0xba, 0x46, 0x75, 0x43, 0x40, 0x92, 0x43, 0xf0, 0xda, 0xe7, 0x59, 0x7c, 0x38, 0xa8, 0x88, 0xc5,
	0x5e, 0x1a, 0xae, 0xae, 0xb2, 0x21, 0x3b, 0x23, 0xca, 0xc7, 0x65, 0xf2, 0xcb, 0x60, 0x4e, 0x12,
	0x1f, 0x21, 0xd8, 0x48, 0xb1, 0x93, 0x26, 0x62, 0x31, 0x4b, 0xc3, 0xd5, 0xf5, 0xd9, 0xc1, 0xb0,
	0xe2, 0xa3, 0x05, 0xd7, 0xb0, 0xd8, 0x9e, 0xca, 0x6d, 0x34, 0xa3, 0x8e, 0xe3, 0xc9, 0x64, 0xc7,
	0xcf, 0x8c, 0x78, 0x0b, 0x41, 0x2d, 0x9b, 0xaa, 0x76, 0x91, 0x17, 0xb3, 0xd4, 0xe7, 0xe3, 0x84,
	0xf7, 0x00, 0x5a, 0x18, 0xd9, 0xb9, 0x8d, 0xb0, 0x75, 0xe4, 0xc7, 0x2c, 0x5d, 0xf0, 0x09, 0x49,
	0x3e, 0x21, 0x9c, 0xbc, 0x03, 0x11, 0x7c, 0x32, 0x32, 0x32, 0x92, 0xc6, 0x25, 0x5c, 0xbc, 0x1b,
	0xf9, 0x5d, 0xf7, 0x7c, 0x46, 0xfc, 0x38, 0xe3, 0x0d, 0xcc, 0xdf, 0x54, 0x57, 0x4a, 0x6a, 0xf5,
	0xf8, 0x30, 0xe0, 0x1d, 0x5c, 0x6e, 0x9b, 0x56, 0x5a, 0x27, 0x5a, 0x4d, 0x9d, 0x1e, 0x3f, 0x81,
	0x22, 0xa0, 0x2f, 0x7d, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa1, 0x83, 0x2c, 0xc8, 0x01,
	0x00, 0x00,
}
